[project]
name = "yolo-forge"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "win-64", "osx-64", "osx-arm64"]

[feature.build.tasks]
build = "rattler-build build -c conda-forge -c https://prefix.dev/yolo-forge --recipe "

[feature.build.dependencies]
rattler-build = ">=0.37.0"

[feature.lint.dependencies]
check-jsonschema = "*"
shellcheck = "*"
pre-commit = "*"
pre-commit-hooks = "*"
taplo = "*"
typos = "*"

[feature.lint.tasks]
pre-commit-install = "pre-commit install"
lint = "pre-commit run -a"

[environments]
default = ["build", "lint"]
lint = ["lint"]
