context:
  name: starship-fork-pavelzw
  version: '1.22.1'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/pavelzw/starship/archive/bf0cbbf18ca29e1cdc57a2cf3a47331de539b0da.tar.gz
  sha256: 600acb0006e976e8b76dc3eeddbc9c2519bb074403ce04a1238929f82118beb8

build:
  number: 2

tests:
  - script:
      - starship --version

requirements:
  build:
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  run_exports:
    - starship <0

about:
  repository: https://github.com/pavelzw/starship
  license: ISC
  license_file: LICENSE
  summary: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
