context:
  name: starship-fork-pavelzw
  version: '1.23.0'

package:
  name: ${{ name }}
  version: ${{ version }}

build:
  number: 0

tests:
  - script:
      - starship --version

requirements:
  run:
    - starship >=1.23.0

about:
  repository: https://github.com/pavelzw/starship
  license: ISC
  summary: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
