context:
  name: starship-fork-pavelzw
  version: '1.22.1'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/pavelzw/starship/archive/784ac28e7b7ff845e358de8443825f7ae5af5ace.tar.gz
  sha256: b7c13897eb3ab3f1fe3ba4ef4ba50fd01e3e05423f0e399822475ed647ec3d76

build:
  number: 4

tests:
  - script:
      - starship --version

requirements:
  build:
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  run_constraints:
    - starship <0

about:
  repository: https://github.com/pavelzw/starship
  license: ISC
  license_file: LICENSE
  summary: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
